set(sources ${sources}
	src/DebugMenu/BoxHandler.cpp
	src/DebugMenu/CellHandler.cpp
	src/DebugMenu/CollisionHandler.cpp
	src/DebugMenu/DebugItem.cpp
	src/DebugMenu/DebugMenu.cpp
	src/DebugMenu/InfoHandler.cpp
	src/DebugMenu/MarkerHandler.cpp
	src/DebugMenu/NavmeshHandler.cpp
	src/DebugMenu/RefInspectorHandler.cpp
	src/DebugUIMenu.cpp
	src/DrawHandler.cpp
	src/DrawMenu.cpp
	src/FreeCamHandler.cpp
	src/Interface/AnimationHandler.cpp
	src/Interface/BoundingBox.cpp
	src/Interface/Button.cpp
	src/Interface/Element.cpp
	src/Interface/GroupElement.cpp
	src/Interface/IElement.cpp
	src/Interface/InputHandler.cpp
	src/Interface/Menu.cpp
	src/Interface/Textfield.cpp
	src/Interface/UIHandler.cpp
	src/Interface/UIUtils.cpp
	src/Interface_prismaUI/InterfaceHandler.cpp
	src/Linalg.cpp
	src/MCM.cpp
	src/RE.cpp
	src/Renderer/CBuffer.cpp
	src/Renderer/D3DContext.cpp
	src/Renderer/Drawer.cpp
	src/Renderer/MeshDrawer.cpp
	src/Renderer/Model.cpp
	src/Renderer/Renderer.cpp
	src/Renderer/Shaders.cpp
	src/Renderer/VertexBuffer.cpp
	src/Utils.cpp
	src/main.cpp
)
